services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_DB: ai-agent-db
      POSTGRES_USER: chatuser
      POSTGRES_PASSWORD: chatpass
    ports:
      - "5432:5432"
    networks:
      - spring-ai-network

  spring-ai-agent:
    image: spring-ai-agent:0.0.1-SNAPSHOT
    container_name: spring-ai-app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: XXX
      AWS_SECRET_ACCESS_KEY: YYY
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ai-agent-db
      SPRING_DATASOURCE_USERNAME: chatuser
      SPRING_DATASOURCE_PASSWORD: chatpass
    networks:
      - spring-ai-network

networks:
  spring-ai-network: