spring:
  application:
    name: sample-authorization-server
  security:
    oauth2:
      authorizationserver:
        client:
          default-client:
            token:
              access-token-time-to-live: 1h
            registration:
              client-id: "default-client"
              client-secret: "{noop}default-secret"
              client-authentication-methods:
                - "client_secret_basic"
                - "client_secret_post"
                - "none"
              authorization-grant-types:
                - "authorization_code"
                - "client_credentials"
              redirect-uris:
                - "http://127.0.0.1:8080/authorize/oauth2/code/authserver"
                - "http://localhost:8080/authorize/oauth2/code/authserver"
                - "http://127.0.0.1:8080/login/oauth2/code/authserver"
                - "http://localhost:8080/login/oauth2/code/authserver"
                - "http://127.0.0.1:8081/authorize/oauth2/code/authserver"
                - "http://localhost:8081/authorize/oauth2/code/authserver"
                - "http://127.0.0.1:8081/login/oauth2/code/authserver"
                - "http://localhost:8081/login/oauth2/code/authserver"
                - "http://127.0.0.1:8090/authorize/oauth2/code/authserver"
                - "http://localhost:8090/authorize/oauth2/code/authserver"
                - "http://127.0.0.1:8090/login/oauth2/code/authserver"
                - "http://localhost:8090/login/oauth2/code/authserver"
                - "http://127.0.0.1:8091/authorize/oauth2/code/authserver"
                - "http://localhost:8091/authorize/oauth2/code/authserver"
                - "http://127.0.0.1:8091/login/oauth2/code/authserver"
                - "http://localhost:8091/login/oauth2/code/authserver"
                - "http://localhost:6274/oauth/callback" # mcp-inspector
                - "http://localhost:6274/oauth/callback/debug" # mcp-inspector
                - "https://claude.ai/api/mcp/auth_callback"
                - "http://localhost:35535/oauth/callback"
              scopes:
                - openid
                - email
                - profile
    user:
      name: user
      password: password

server:
  port: ${PORT:9000}
  servlet:
    session:
      cookie:
        name: MCP_AUTHORIZATION_SERVER_SESSIONID
logging:
  level:
    org.springframework.security: TRACE