# Harness Pipeline Values Override
# These values are populated by Harness expressions during deployment

release:
  version: <+pipeline.sequenceId>
  versionUrl: <+pipeline.stages.Build.spec.execution.steps.Build_and_Push_to_ECR.artifact_Build_and_Push_to_ECR.stepArtifacts.publishedImageArtifacts[1].url>
  deploymentTime: <+pipeline.stages.Build.spec.execution.steps.Build_and_Push_to_ECR.artifact_Build_and_Push_to_ECR.stepArtifacts.provenanceArtifacts[0].predicate.runDetails.metadata.finishedOn>
  commit: <+codebase.shortCommitSha>
  environment: <+infra.name>
